micronaut:
  application:
    name: futurebattlegrounds
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
      swagger:
        enabled: true
        paths:
          - classpath:META-INF/swagger
          - classpath:swagger
        mapping: /swagger/**
